name: Publish
on:
  schedule:
    - cron: '33 3 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Netlify CLI
        run: npm install -g netlify-cli@16.0.2
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout Scryer Prolog
        uses: actions/checkout@v4
        with:
          repository: mthom/scryer-prolog
          path: scryer-prolog
      - name: Compile Scryer Prolog
        run: cargo build --release
        working-directory: scryer-prolog
      - name: Install Scryer Prolog
        run: sudo cp scryer-prolog/target/release/scryer-prolog /usr/bin/scryer-prolog
      - name: Install Dependencies
        run: make setup
      - name: Generate docs for https://www.scryer.pl
        run: make
      - name: Upload site
        run: netlify deploy --prod --dir=output
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
